@extends('layouts.app')

@foreach( $home->meta as $metaKey => $metaValue )
    <meta {{ $metaKey }} content="{{ $metaValue }}">
@endforeach

@section('content')

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body style="padding:0px; margin:0px; background-color:#fff;font-family:Arial, sans-serif">

    <!-- #region Jssor Slider Begin -->
    <!-- Generated by Jssor Slider Maker Online. -->
    <!-- This demo works with jquery library -->

    <script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="js/jssor.slider.mini.js"></script>
    <!-- use jssor.slider.debug.js instead for debug -->
    <script>
        jQuery(document).ready(function ($) {

            var jssor_1_SlideoTransitions = [
              
            ];

            var jssor_1_options = {
                $AutoPlay: true,
                $SlideDuration: 2000,
                $SlideEasing: $Jease$.$OutQuint,
                $CaptionSliderOptions: {
                    $Class: $JssorCaptionSlideo$,
                    $Transitions: jssor_1_SlideoTransitions
                },
                $ArrowNavigatorOptions: {
                    $Class: $JssorArrowNavigator$
                },
                $BulletNavigatorOptions: {
                    $Class: $JssorBulletNavigator$
                }
            };

            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizing
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 2440);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>

    <style>
        /* jssor slider bullet navigator skin 05 css */
        /*
        .jssorb05 div           (normal)
        .jssorb05 div:hover     (normal mouseover)
        .jssorb05 .av           (active)
        .jssorb05 .av:hover     (active mouseover)
        .jssorb05 .dn           (mousedown)
        */
        .jssorb05 {
            position: absolute;
        }

            .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
                position: absolute;
                /* size of bullet elment */
                width: 16px;
                height: 16px;
                background: url('img/b14.png') no-repeat;
                overflow: hidden;
                cursor: pointer;
            }

            .jssorb05 div {
                background-position: -7px -7px;
            }

                .jssorb05 div:hover, .jssorb05 .av:hover {
                    background-position: -37px -7px;
                }

            .jssorb05 .av {
                background-position: -67px -7px;
            }

            .jssorb05 .dn, .jssorb05 .dn:hover {
                background-position: -97px -7px;
            }

        /* jssor slider arrow navigator skin 22 css */
        /*
        .jssora22l                  (normal)
        .jssora22r                  (normal)
        .jssora22l:hover            (normal mouseover)
        .jssora22r:hover            (normal mouseover)
        .jssora22l.jssora22ldn      (mousedown)
        .jssora22r.jssora22rdn      (mousedown)
        */
        .jssora22l, .jssora22r {
            display: block;
            position: absolute;
            /* size of arrow element */
            width: 40px;
            height: 58px;
            cursor: pointer;
            background: url('img/a16.png') center center no-repeat;
            overflow: hidden;
        }

        .jssora22l {
            background-position: -10px -31px;
        }

        .jssora22r {
            background-position: -70px -31px;
        }

        .jssora22l:hover {
            background-position: -130px -31px;
        }

        .jssora22r:hover {
            background-position: -190px -31px;
        }

        .jssora22l.jssora22ldn {
            background-position: -250px -31px;
        }

        .jssora22r.jssora22rdn {
            background-position: -310px -31px;
        }
    </style>


    <div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 1300px; height: 500px; overflow: hidden; visibility: hidden;">
        <!-- Loading Screen -->
        <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
            <div style="position:absolute;display:block;background:url('../public/img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
        </div>
        
        <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 1300px; height: 500px; overflow: hidden;">
            @foreach( $home->banner as $banner )
            <div data-p="225.00" style="display: none;">
                <div class="home_bntitle"><img src="/img/pics/banner_title-02.png"/></div>
                <div class="home_banner1" style="background-image:url({{ $banner->image }});" data-u="image" >
                </div>
                
            </div>
            @endforeach
        </div>
        <!-- Bullet Navigator -->
        <div data-u="navigator" class="jssorb05" style="bottom:16px;right:16px;" data-autocenter="1">
            <!-- bullet navigator item prototype -->
            <div data-u="prototype" style="width:16px;height:16px;"></div>
        </div>
        <!-- Arrow Navigator -->
        <span data-u="arrowleft" class="jssora22l" style="top:0px;left:12px;width:40px;height:58px;" data-autocenter="2"></span>
        <span data-u="arrowright" class="jssora22r" style="top:0px;right:12px;width:40px;height:58px;" data-autocenter="2"></span>
    </div>



<div class="home-container">
    <div class="row">
        <div class="panel-filter">
            <select name="type" id="types" >
                <option style="display:none">想和誰去</option>
                @foreach( $home->filter->who as $key_with => $with_who )
                    <option value="{{ $key_with }}"> {{ $with_who }} </option>
                @endforeach
            </select>

            <select name="type" id="types" >
                <option style="display:none">想玩什麼</option>
                @foreach( $home->filter->what as $key_play => $play_what )
                    <option value="{{ $key_play }}"> {{ $play_what }} </option>
                @endforeach
            </select>

            <select name="type" id="types" >
                <option style="display:none">想去哪兒</option>
                @foreach( $home->filter->where as $key_where => $go_where )
                    <option value="{{ $key_where }}"> {{ $go_where }} </option>
                @endforeach
            </select>

            <select name="type" id="types" >
                <option style="display:none">預算多少</option>
                @foreach( $home->filter->price as $key_price => $price )
                    <option value="{{ $key_price }}"> {{ $price }} </option>
                @endforeach
            </select>
        </div>
    </div>
    
        <div class="home-container">
            <div class="home-blog">
                <div class="row home-title"><img src="/img/pics/new_articles-02.png">
                </div>
                <div class="row home-blog-contain">
                @foreach( $home->newBlog as $blog )
                    <div class="col-lg-6 col-md-6 col-sm-12 home-blog-panel">
                        <div class="home-blog-thumbnail" style="background-image:url({{ $blog->thumbnail }})">      
                        </div>
                        <div class="home-blog-title">       {{ $blog->title }}       </div>
                        <div class="home-blog-created_at">  {{ $blog->created_at }}  </div>
                        <div class="glyphicon glyphicon-folder-open home-blog-category">    {{ $blog->category }}    </div>
                        <div class="glyphicon glyphicon-user home-blog-author">      {{ $blog->author }}      </div>
                        <div class="home-blog-description word-indent"> {{ $blog->description }} </div>
                    </div>
                @endforeach
                </div>
                <div class="row home-read-more">閱讀更多</div>
            </div>

            <div class="home-new-activity">
                <div class="row home-title"><img src="/img/pics/new_activities-02.png"></div>
                <div class="row home-new-activity-contain">
                @foreach( $home->newActivity as $newActivity )
                    <div class="col-lg-4 col-md-6 col-sm-12 home-new-activity-panel">
                        <div class="newact_panel_bg">
                        <div class="home-new-activity-id">          {{ $newActivity->activity_id }} </div>
                        <div class="home-new-activity-thumbnail" style="background-image:url({{ $newActivity->thumbnail }})">    
                        </div>
                        
                        <div class="home-new-activity-title">       {{ $newActivity->title }}       </div>
                        <div class="home-new-activity-count">       {{ $newActivity->count }}  人    </div>
                        <div class="home-new-activity-description word-indent"> {{ $newActivity->description }} </div>
                        <div class="home-new-activity-price">  <img src="img/pics/money-icon-02.png">     {{ $newActivity->price }}   元    </div>
                        <div class="home-new-activity-date">   <img src="img/pics/calendar-icon-02.png">     {{ $newActivity->date }}        </div>
                        <div class="home-new-activity-location">  <img src="img/pics/location-icon-02.png">    {{ $newActivity->location }}    </div>
                        <div class="home-new-activity-orginizer">  --- {{ $newActivity->orginizer }} --- </div>
                        </div>
                    </div>
                @endforeach
                </div>
            </div>

            <div class="total-activity">
                <div class="row home-title"><img src="/img/pics/act_category-02.png"></div>
                <div class="total-activity-contain">
                @foreach( $home->totalActivity as $eachTypeActivity )
                    <div class="outer-panel">
                        <div class="activity-category-id">          {{ $eachTypeActivity->cat_id }}         </div>
                        <div class="activity-category-thumbnail" style="background-image:url({{ $eachTypeActivity->cat_thumbnail }})"> 
                        </div>
                        <div class="activity-category-title">       {{ $eachTypeActivity->cat_title }}      </div>
                        <div class="activity-category-logo">        {{ $eachTypeActivity->cat_logo }}       </div>
                        <div class="activity-category-content">
                            @foreach( $eachTypeActivity->cat_content as $activity )
                                <div class="inter-panel">
                                    <div class="activity-id">          {{ $newActivity->activity_id }} </div>
                                    <div class="activity-title">       {{ $newActivity->title }}       </div>
                                    <div class="activity-count">       {{ $newActivity->count }}       </div>
                                    <div class="activity-thumbnail">   {{ $newActivity->thumbnail }}   </div>
                                    <div class="activity-description"> {{ $newActivity->description }} </div>
                                    <div class="activity-price">       {{ $newActivity->price }}       </div>
                                    <div class="activity-date">        {{ $newActivity->date }}        </div>
                                    <div class="activity-location">    {{ $newActivity->location }}    </div>
                                    <div class="activity-orginizer">   {{ $newActivity->orginizer }}   </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endforeach
                </div>
            </div>
        </div>
    
</div>
@endsection
